
interface _GlobalComponents {
      'CoffeeHero': typeof import("../components/CoffeeHero.vue")['default']
    'CoffeeInfo': typeof import("../components/CoffeeInfo.vue")['default']
    'ContactForm': typeof import("../components/ContactForm.vue")['default']
    'ContactInfo': typeof import("../components/ContactInfo.vue")['default']
    'Footer': typeof import("../components/Footer.vue")['default']
    'FourCard': typeof import("../components/FourCard.vue")['default']
    'InteractiveMap': typeof import("../components/InteractiveMap.vue")['default']
    'MainHero': typeof import("../components/MainHero.vue")['default']
    'MainInfo': typeof import("../components/MainInfo.vue")['default']
    'Navbar': typeof import("../components/Navbar.vue")['default']
    'RestaurantHero': typeof import("../components/RestaurantHero.vue")['default']
    'RestaurantInfo': typeof import("../components/RestaurantInfo.vue")['default']
    'ShoppingHero': typeof import("../components/ShoppingHero.vue")['default']
    'ShoppingInfo': typeof import("../components/ShoppingInfo.vue")['default']
    'ThingsToDoHero': typeof import("../components/ThingsToDoHero.vue")['default']
    'ThingsToDoInfo': typeof import("../components/ThingsToDoInfo.vue")['default']
    'MapboxAttributionControl': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/AttributionControl.vue")['default']
    'MapboxCustomGeocoder': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/CustomGeocoder.vue")['default']
    'MapboxDefaultMarker': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/DefaultMarker.vue")['default']
    'MapboxDefaultPopup': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/DefaultPopup.vue")['default']
    'MapboxFullscreenControl': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/FullscreenControl.vue")['default']
    'MapboxGeocoder': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/Geocoder.vue")['default']
    'MapboxGeolocateControl': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/GeolocateControl.vue")['default']
    'MapboxLayer': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/Layer.vue")['default']
    'MapboxMap': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/Map.vue")['default']
    'MapboxNavigationControl': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/NavigationControl.vue")['default']
    'MapboxScaleControl': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/ScaleControl.vue")['default']
    'MapboxSource': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/Source.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyCoffeeHero': typeof import("../components/CoffeeHero.vue")['default']
    'LazyCoffeeInfo': typeof import("../components/CoffeeInfo.vue")['default']
    'LazyContactForm': typeof import("../components/ContactForm.vue")['default']
    'LazyContactInfo': typeof import("../components/ContactInfo.vue")['default']
    'LazyFooter': typeof import("../components/Footer.vue")['default']
    'LazyFourCard': typeof import("../components/FourCard.vue")['default']
    'LazyInteractiveMap': typeof import("../components/InteractiveMap.vue")['default']
    'LazyMainHero': typeof import("../components/MainHero.vue")['default']
    'LazyMainInfo': typeof import("../components/MainInfo.vue")['default']
    'LazyNavbar': typeof import("../components/Navbar.vue")['default']
    'LazyRestaurantHero': typeof import("../components/RestaurantHero.vue")['default']
    'LazyRestaurantInfo': typeof import("../components/RestaurantInfo.vue")['default']
    'LazyShoppingHero': typeof import("../components/ShoppingHero.vue")['default']
    'LazyShoppingInfo': typeof import("../components/ShoppingInfo.vue")['default']
    'LazyThingsToDoHero': typeof import("../components/ThingsToDoHero.vue")['default']
    'LazyThingsToDoInfo': typeof import("../components/ThingsToDoInfo.vue")['default']
    'LazyMapboxAttributionControl': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/AttributionControl.vue")['default']
    'LazyMapboxCustomGeocoder': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/CustomGeocoder.vue")['default']
    'LazyMapboxDefaultMarker': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/DefaultMarker.vue")['default']
    'LazyMapboxDefaultPopup': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/DefaultPopup.vue")['default']
    'LazyMapboxFullscreenControl': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/FullscreenControl.vue")['default']
    'LazyMapboxGeocoder': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/Geocoder.vue")['default']
    'LazyMapboxGeolocateControl': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/GeolocateControl.vue")['default']
    'LazyMapboxLayer': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/Layer.vue")['default']
    'LazyMapboxMap': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/Map.vue")['default']
    'LazyMapboxNavigationControl': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/NavigationControl.vue")['default']
    'LazyMapboxScaleControl': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/ScaleControl.vue")['default']
    'LazyMapboxSource': typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/Source.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CoffeeHero: typeof import("../components/CoffeeHero.vue")['default']
export const CoffeeInfo: typeof import("../components/CoffeeInfo.vue")['default']
export const ContactForm: typeof import("../components/ContactForm.vue")['default']
export const ContactInfo: typeof import("../components/ContactInfo.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const FourCard: typeof import("../components/FourCard.vue")['default']
export const InteractiveMap: typeof import("../components/InteractiveMap.vue")['default']
export const MainHero: typeof import("../components/MainHero.vue")['default']
export const MainInfo: typeof import("../components/MainInfo.vue")['default']
export const Navbar: typeof import("../components/Navbar.vue")['default']
export const RestaurantHero: typeof import("../components/RestaurantHero.vue")['default']
export const RestaurantInfo: typeof import("../components/RestaurantInfo.vue")['default']
export const ShoppingHero: typeof import("../components/ShoppingHero.vue")['default']
export const ShoppingInfo: typeof import("../components/ShoppingInfo.vue")['default']
export const ThingsToDoHero: typeof import("../components/ThingsToDoHero.vue")['default']
export const ThingsToDoInfo: typeof import("../components/ThingsToDoInfo.vue")['default']
export const MapboxAttributionControl: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/AttributionControl.vue")['default']
export const MapboxCustomGeocoder: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/CustomGeocoder.vue")['default']
export const MapboxDefaultMarker: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/DefaultMarker.vue")['default']
export const MapboxDefaultPopup: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/DefaultPopup.vue")['default']
export const MapboxFullscreenControl: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/FullscreenControl.vue")['default']
export const MapboxGeocoder: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/Geocoder.vue")['default']
export const MapboxGeolocateControl: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/GeolocateControl.vue")['default']
export const MapboxLayer: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/Layer.vue")['default']
export const MapboxMap: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/Map.vue")['default']
export const MapboxNavigationControl: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/NavigationControl.vue")['default']
export const MapboxScaleControl: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/ScaleControl.vue")['default']
export const MapboxSource: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/Source.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyCoffeeHero: typeof import("../components/CoffeeHero.vue")['default']
export const LazyCoffeeInfo: typeof import("../components/CoffeeInfo.vue")['default']
export const LazyContactForm: typeof import("../components/ContactForm.vue")['default']
export const LazyContactInfo: typeof import("../components/ContactInfo.vue")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyFourCard: typeof import("../components/FourCard.vue")['default']
export const LazyInteractiveMap: typeof import("../components/InteractiveMap.vue")['default']
export const LazyMainHero: typeof import("../components/MainHero.vue")['default']
export const LazyMainInfo: typeof import("../components/MainInfo.vue")['default']
export const LazyNavbar: typeof import("../components/Navbar.vue")['default']
export const LazyRestaurantHero: typeof import("../components/RestaurantHero.vue")['default']
export const LazyRestaurantInfo: typeof import("../components/RestaurantInfo.vue")['default']
export const LazyShoppingHero: typeof import("../components/ShoppingHero.vue")['default']
export const LazyShoppingInfo: typeof import("../components/ShoppingInfo.vue")['default']
export const LazyThingsToDoHero: typeof import("../components/ThingsToDoHero.vue")['default']
export const LazyThingsToDoInfo: typeof import("../components/ThingsToDoInfo.vue")['default']
export const LazyMapboxAttributionControl: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/AttributionControl.vue")['default']
export const LazyMapboxCustomGeocoder: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/CustomGeocoder.vue")['default']
export const LazyMapboxDefaultMarker: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/DefaultMarker.vue")['default']
export const LazyMapboxDefaultPopup: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/DefaultPopup.vue")['default']
export const LazyMapboxFullscreenControl: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/FullscreenControl.vue")['default']
export const LazyMapboxGeocoder: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/Geocoder.vue")['default']
export const LazyMapboxGeolocateControl: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/GeolocateControl.vue")['default']
export const LazyMapboxLayer: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/Layer.vue")['default']
export const LazyMapboxMap: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/Map.vue")['default']
export const LazyMapboxNavigationControl: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/NavigationControl.vue")['default']
export const LazyMapboxScaleControl: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/ScaleControl.vue")['default']
export const LazyMapboxSource: typeof import("../node_modules/nuxt-mapbox/dist/runtime/components/Source.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
